#!/usr/bin/env python3
from __future__ import annotations

import re
import shutil
from pathlib import Path


VAULT = Path(__file__).resolve().parents[1]
DAILY_ROOT = VAULT / "daily_notes"
OUT = VAULT / "Machine" / "TaskGantt" / "Start-of-Day"


def yaml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def safe_filename(value: str) -> str:
    clean = re.sub(r'[\\/:*?"<>|#^\[\]]+', " ", value)
    clean = re.sub(r"\s+", " ", clean).strip()
    return clean[:90].rstrip(" .") or "Task"


def date_from_path(path: Path) -> str | None:
    rel = path.relative_to(VAULT).as_posix()
    match = re.match(r"daily_notes/(\d{4})/(\d{2})/(\d{2})\.md$", rel)
    return f"{match.group(1)}-{match.group(2)}-{match.group(3)}" if match else None


def extract_date(text: str, marker: str) -> str | None:
    match = re.search(rf"{re.escape(marker)}\s*(\d{{4}}-\d{{2}}-\d{{2}})", text)
    return match.group(1) if match else None


def priority(text: str) -> str:
    if "⏫" in text:
        return "highest"
    if "🔼" in text:
        return "high"
    if "🔺" in text:
        return "medium"
    if "🔽" in text:
        return "low"
    if "⏬" in text:
        return "lowest"
    return "normal"


def iter_start_of_day_tasks() -> list[dict[str, str | int]]:
    rows: list[dict[str, str | int]] = []
    for path in sorted(DAILY_ROOT.glob("*/*/*.md")):
        note_date = date_from_path(path)
        if not note_date:
            continue

        lines = path.read_text(encoding="utf-8").splitlines()
        try:
            start = next(i for i, line in enumerate(lines) if re.match(r"^## Start of day\s*$", line))
            end = next(i for i, line in enumerate(lines) if i > start and re.match(r"^## End of day\s*$", line))
        except StopIteration:
            continue

        for line_no, line in enumerate(lines[start + 1 : end], start + 2):
            match = re.match(r"^\s*[-*]\s+\[([ xX])\]\s+(.+?)\s*$", line)
            if not match:
                continue
            completed = match.group(1).lower() == "x"
            text = match.group(2).strip()
            task_start = extract_date(text, "🛫") or note_date
            task_end = extract_date(text, "📅") or task_start
            rows.append({
                "text": text,
                "source": path.relative_to(VAULT).as_posix(),
                "line": line_no,
                "start": task_start,
                "end": task_end,
                "completed": completed,
                "priority": priority(text),
            })
    return rows


def write_task(row: dict[str, str | int], index: int) -> None:
    title = str(row["text"])
    filename = f"{index:03d} - {safe_filename(title)}.md"
    path = OUT / filename
    completed = bool(row["completed"])
    tags = ["task-gantt", "start-of-day", f"priority/{row['priority']}"]
    if completed:
        tags.append("done")
    body = "\n".join([
        "---",
        f"start: {row['start']}",
        f"end: {row['end']}",
        f"status: {'done' if completed else 'todo'}",
        f"source: {yaml_string(str(row['source']))}",
        f"source_line: {row['line']}",
        "tags:",
        *(f"  - {tag}" for tag in tags),
        "---",
        "",
        f"- [{'x' if completed else ' '}] {title}",
        "",
        f"Source: [[{str(row['source']).removesuffix('.md')}]]",
        "",
        "<!-- Generated by scripts/sync_task_gantt_start_of_day.py. Edit the source daily note, then rerun sync. -->",
        "",
    ])
    path.write_text(body, encoding="utf-8")


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True, exist_ok=True)

    rows = iter_start_of_day_tasks()
    for index, row in enumerate(rows, start=1):
        write_task(row, index)

    print(f"Synced {len(rows)} start-of-day tasks to {OUT.relative_to(VAULT)}")


if __name__ == "__main__":
    main()
